-- DML

INSERT INTO PRODUCTS
VALUES (1, 'Fender', 'American Ultra', 'ELECTRIC_GUITAR', 4624.85, '', 1);

INSERT INTO PRODUCTS VALUES (2, 'Fender', 'Player', 'ELECTRIC_GUITAR', 2624.85,'', 2);
INSERT INTO PRODUCTS VALUES (3, 'Fender', 'Limited Edition 70th Anniversary Broadcaster Time Capsule','ELECTRIC_GUITAR', 8624.85, '', 1);
INSERT INTO PRODUCTS VALUES (4, 'Ibanez', 'AZES40-MGR', 'ELECTRIC_GUITAR', 4624.85, '', 1);

COMMIT;
